UI update
samzi123/PenPal-Chat-Widget pull request #1
Opened 2023-07-31 00:02 UTC by tamuda

2023-08-01 07:40 UTC, samzi123 requested changes
Overall great work, just a couple of comments. Also, please take a look at how the input textbox scales on mobile screens, as it is very small. See the attached image. Consider adding a breakpoint so that it is bigger on mobile devices.


<img width="349" alt="Screenshot 2023-08-01 at 00 39 38" src="https://github.com/samzi123/PenPal-Chat-Widget/assets/40142534/ed66345a-ab77-4cad-aea1-d42f76b450b8">

2023-08-01 07:40 UTC, samzi123 commented on main31.js
> +//const BASE_URL = "https://sswj8m0la3.execute-api.af-south-1.amazonaws.com/dev/";
Please switch which base url is being used, as we want this to be the live version

2023-08-01 07:40 UTC, samzi123 commented on main31.js
> +        setColorsFromThemeName("dark");
The line above should not be commented out, as we want to set the theme to the one fetched from the DB, rather than being hardcoded.

2023-08-27 19:00 UTC, tamuda commented
I have made the widget responsive

2023-08-27 23:51 UTC, merged

2023-09-05 16:48 UTC, samzi123 approved these changes